class CountryController {
  async continents(request, response, next) {
    try {
      return response.json([
        { continent: "Asia", name: "Ásia" },
        { continent: "Africa", name: "África" },
        { continent: "North America", name: "América do Norte" },
        { continent: "South America", name: "América do Sul" },
        { continent: "Oceania", name: "Oceania" },
        { continent: "Europe", name: "Europa" },
        { continent: "Antarctica", name: "Antártida" },
      ]);
    } catch (error) {
      next(error);
    }
  }

  async countrys(request, response, next) {
    try {
      return response.json([
        {
          Asia: [
            { name: "Japão", code: "JP" },
            { name: "Indonésia", code: "ID" },
            { name: "China", code: "CN" },
            { name: "Índia", code: "IN" },
            { name: "Tailândia", code: "TH" },
            { name: "Filipinas", code: "PH" },
            { name: "Coreia do Sul", code: "KR" },
            { name: "Singapura", code: "SG" },
            { name: "Hong Kong", code: "HK" },
            { name: "Vietnã", code: "VN" },
            { name: "Malásia", code: "MY" },
            { name: "Paquistão", code: "PK" },
            { name: "Myanmar", code: "MM" },
            { name: "Irã", code: "IR" },
            { name: "Uzbequistão", code: "UZ" },
            { name: "Arábia Saudita", code: "SA" },
            { name: "Israel", code: "IL" },
            { name: "Taiwan", code: "TW" },
            { name: "Maldivas", code: "MV" },
            { name: "Camboja", code: "Camboja" },
            { name: "Mongólia", code: "Mongólia" },
            { name: "Afeganistão", code: "AF" },
            { name: "Armênia", code: "AM" },
            { name: "Bangladesh", code: "BD" },
            { name: "Nepal", code: "NP" },
            { name: "Sri Lanka", code: "LK" },
            { name: "Laos", code: "LA" },
            { name: "Coreia do Norte", code: "KP" },
            { name: "Iraque", code: "IQ" },
            { name: "Macau", code: "MO" },
            { name: "Síria", code: "SY" },
            { name: "Catar", code: "QA" },
            { name: "Emirados Árabes Unidos", code: "AE" },
            { name: "Brunei", code: "BN" },
            { name: "Líbano", code: "LB" },
            { name: "Ilha Christmas", code: "CX" },
            { name: "Iêmen", code: "YE" },
            { name: "Jordânia", code: "JO" },
            { name: "Kuwait", code: "KW" },
            { name: "Palestina", code: "PS" },
            { name: "Butão", code: "BT" },
            { name: "Território do Oceano Índico Britânico", code: "IO" },
            { name: "Timor-Leste", code: "TL" },
            { name: "Quirguistão", code: "KG" },
            { name: "Tajiquistão", code: "TJ" },
            { name: "Turcomenistão", code: "TM" },
            { name: "Bahrein", code: "BH" },
            { name: "Omã", code: "OM" },
            { name: "Ilhas Cocos (Keeling)", code: "CC" },
          ],
          Africa: [
            { name: "África do Sul", code: "ZA" },
            { name: "Nigéria", code: "NG" },
            { name: "Gana", code: "GH" },
            { name: "Quênia", code: "KE" },
            { name: "Etiópia", code: "ET" },
            { name: "Tanzânia", code: "TZ" },
            { name: "República Democrática do Congo", code: "CD" },
            { name: "Marrocos", code: "MA" },
            { name: "Senegal", code: "SN" },
            { name: "Mali", code: "ML" },
            { name: "Uganda", code: "UG" },
            { name: "Sudão", code: "SD" },
            { name: "Zâmbia", code: "ZM" },
            { name: "Madagascar", code: "MG" },
            { name: "Somália", code: "SO" },
            { name: "Costa do Marfim", code: "CI" },
            { name: "Angola", code: "AO" },
            { name: "Camarões", code: "CM" },
            { name: "Zimbábue", code: "ZW" },
            { name: "Argélia", code: "DZ" },
            { name: "Ruanda", code: "RW" },
            { name: "Namíbia", code: "NA" },
            { name: "República Centro-Africana", code: "CF" },
            { name: "Níger", code: "NE" },
            { name: "Moçambique", code: "MZ" },
            { name: "Guiné-Conacri", code: "GW" },
            { name: "Líbia", code: "LY" },
            { name: "Libéria", code: "Libéria" },
            { name: "Tunísia", code: "TN" },
            { name: "Malawi", code: "MW" },
            { name: "Burkina Faso", code: "BF" },
            { name: "Botsuana", code: "BW" },
            { name: "Gâmbia", code: "GM" },
            { name: "Togo", code: "TG" },
            { name: "Chade", code: "TD" },
            { name: "Mauritânia", code: "MR" },
            { name: "Cabo Verde", code: "CV" },
            { name: "Serra Leoa", code: "SL" },
            { name: "Benin", code: "BJ" },
            { name: "Eritreia", code: "ER" },
            { name: "Ilhas Maurício", code: "MU" },
            { name: "Gabão", code: "GA" },
            { name: "Djibouti", code: "DJ" },
            { name: "Sudão do Sul", code: "SS" },
            { name: "Saara Ocidental", code: "EH" },
            { name: "República do Congo", code: "CG" },
            { name: "Suazilândia", code: "SZ" },
            { name: "Lesoto", code: "LS" },
            { name: "Burundi", code: "BI" },
            { name: "Guiné Equatorial", code: "GQ" },
            { name: "Seychelles", code: "SC" },
          ],
          NorthAmerica: [
            { name: "Estados Unidos", code: "US" },
            { name: "Groenlândia", code: "GL" },
            { name: "Canadá", code: "CA" },
            { name: "México", code: "MX" },
            { name: "Cuba", code: "CU" },
            { name: "Panamá", code: "PA" },
            { name: "Jamaica", code: "JM" },
            { name: "Haiti", code: "HT" },
            { name: "Costa Rica", code: "CR	" },
            { name: "Guatemala", code: "GT" },
            { name: "República Dominicana", code: "DO" },
            { name: "Porto Rico", code: "PR" },
            { name: "Bahamas", code: "BS" },
            { name: "Barbados", code: "BB" },
            { name: "Granada", code: "GD" },
            { name: "Belize", code: "BZ" },
            { name: "Martinica", code: "MQ" },
            { name: "Honduras", code: "HN" },
            { name: "Ilhas Cayman", code: "KY" },
            { name: "Dominica", code: "DM" },
            { name: "São Bartolomeu", code: "BL" },
            { name: "Nicarágua", code: "NI" },
            { name: "El Salvador", code: "SV" },
            { name: "Ilhas Virgens Americanas", code: "VI" },
            { name: "Saint-Martin", code: "MF" },
            { name: "Antígua e Barbuda", code: "AG" },
            { name: "Ilhas Virgens Britânicas", code: "VG" },
            { name: "Saint-Pierre e Miquelon", code: "PM" },
            { name: "Santa Lúcia", code: "LC" },
            { name: "Turks e Caicos", code: "TC" },
            { name: "Guadalupe", code: "GP" },
            { name: "Anguilla", code: "AI" },
            { name: "São Cristóvão e Neves", code: "KN" },
            { name: "São Vicente e Granadinas", code: "VC" },
            { name: "Sint Maarten", code: "SX" },
            { name: "Montserrat", code: "MS" },
            { name: "Ilhas Menores Distantes dos Estados Unidos", code: "UM" },
          ],
          SouthAmerica: [
            { name: "Brasil", code: "BR" },
            { name: "Argentina", code: "AR" },
            { name: "Colômbia", code: "CO" },
            { name: "Peru", code: "PE" },
            { name: "Chile", code: "CL" },
            { name: "Venezuela", code: "VE" },
            { name: "Equador", code: "EQ" },
            { name: "Bolívia", code: "BO" },
            { name: "Guiana", code: "GY" },
            { name: "Uruguai", code: "UY" },
            { name: "Suriname", code: "SR" },
            { name: "Paraguai", code: "PY" },
            { name: "Guiana Francesa", code: "GF" },
            { name: "Ilhas Malvinas", code: "FK" },
            { name: "Trindade e Tobago", code: "TT" },
            { name: "Aruba", code: "AW" },
            { name: "Curaçao", code: "CW" },
            { name: "Países Baixos Caribenhos", code: "BQ" },
          ],
          Oceania: [
            { name: "Austrália", code: "AU" },
            { name: "Nova Zelândia", code: "NZ" },
            { name: "Fiji", code: "FJ" },
            { name: "Papua-Nova Guiné", code: "PG" },
            { name: "Samoa", code: "WS" },
            { name: "Estados Federados da Micronésia", code: "FM" },
            { name: "Tonga", code: "TO" },
            { name: "Palau", code: "PW" },
            { name: "Vanuatu", code: "VU" },
            { name: "Kiribati", code: "KI" },
            { name: "Ilhas Salomão", code: "SB" },
            { name: "Polinésia Francesa", code: "PF" },
            { name: "Guam", code: "GU" },
            { name: "Tuvalu", code: "TV" },
            { name: "Nova Caledônia", code: "NC" },
            { name: "Ilhas Marshall", code: "MH" },
            { name: "Nauru", code: "NR" },
            { name: "Ilhas Cook", code: "CK" },
            { name: "Samoa Americana", code: "AS" },
            { name: "Ilha Norfolk", code: "NF" },
            { name: "Niue", code: "NU" },
            { name: "Wallis e Futuna", code: "WF" },
            { name: "Ilhas Marianas do Norte", code: "MP" },
            { name: "Ilhas Pitcairn", code: "PN" },
          ],
          Europe: [
            { name: "Alemanha", code: "DE" },
            { name: "França", code: "FR" },
            { name: "Itália", code: "IT" },
            { name: "Reino Unido", code: "GB" },
            { name: "Países Baixos", code: "NL" },
            { name: "Suécia", code: "SE" },
            { name: "Suíça", code: "CH" },
            { name: "Polônia", code: "PL" },
            { name: "Grécia", code: "GR" },
            { name: "Bélgica", code: "BE" },
            { name: "Áustria", code: "AT" },
            { name: "Chéquia", code: "CZ" },
            { name: "Irlanda", code: "IE" },
            { name: "Dinamarca", code: "DK" },
            { name: "Noruega", code: "NO" },
            { name: "Finlândia", code: "FI" },
            { name: "Ucrânia", code: "UA" },
            { name: "Romênia", code: "RO" },
            { name: "Croácia", code: "HR" },
            { name: "Islândia", code: "IS" },
            { name: "Hungria", code: "HU" },
            { name: "Luxemburgo", code: "LU" },
            { name: "Malta", code: "MT" },
            { name: "Bulgária", code: "BG" },
            { name: "Chipre", code: "CY" },
            { name: "Bielorrússia", code: "BY" },
            { name: "Sérvia", code: "RS" },
            { name: "Albânia", code: "AL" },
            { name: "Eslovênia", code: "SI" },
            { name: "Lituânia", code: "LT" },
            { name: "Eslováquia", code: "SK" },
            { name: "Moldávia", code: "MD" },
            { name: "Estônia", code: "EE" },
            { name: "Liechtenstein", code: "LI	" },
            { name: "Letônia", code: "LV" },
            { name: "Mônaco", code: "MC" },
            { name: "Andorra", code: "AD" },
            { name: "Bósnia", code: "BA" },
            { name: "Vaticano", code: "VA" },
            { name: "Macedónia do Norte", code: "MK" },
            { name: "Kosovo", code: "XK" },
            { name: "Montenegro", code: "ME" },
            { name: "San Marino", code: "SM" },
            { name: "Gibraltar", code: "GI" },
            { name: "Ilhas Faroé", code: "FO" },
            { name: "Ilha de Man", code: "IM" },
            { name: "Jersey", code: "JE" },
            { name: "Åland", code: "AX" },
            { name: "Svalbard e Jan Mayen", code: "SJ" },
          ],
          Antarctica: [{ name: "Antártida", code: "AQ" }],
        },
      ]);
    } catch (error) {
      next(error);
    }
  }
}

module.exports = new CountryController();
